import type {
  Alert,
  AlertSeverity,
  AlertCategory,
  AlertUrgency,
  AlertCertainty,
  AlertResponseType,
  AlertSender,
  AlertStatus,
  AlertMsgType,
  AlertScope,
  SOSRequest,
  SOSType,
  SOSEmergencyLevel,
  SOSStatus,
  SOSLocation,
  SOSSituation,
  SOSContact,
  SOSTimeline,
  EmergencyContact,
  EmergencyContactType,
  ChecklistItem,
  ChecklistCategory,
  ChecklistPriority,
  ChecklistSeason,
  ChecklistRegion,
} from "../lib/types";
import type { DisasterType } from "@/lib/types";

// =============================================================================
// ALERT & SOS MODULE - Mock Data
// 20 Alerts | 30 SOS | 15 Provinces Emergency Contacts | 18 Checklist Items
// =============================================================================

// ---------------------------------------------------------------------------
// HELPER: Generate UUID-like IDs
// ---------------------------------------------------------------------------

let _idCounter = 0;
function generateId(prefix: string): string {
  _idCounter++;
  const ts = Date.now().toString(36);
  const rand = Math.random().toString(36).substring(2, 8);
  return `${prefix}-${ts}-${rand}-${_idCounter}`;
}

function randomPastDate(daysBack: number): string {
  const now = Date.now();
  const offset = Math.random() * daysBack * 24 * 60 * 60 * 1000;
  return new Date(now - offset).toISOString();
}

function randomFutureDate(daysAhead: number): string {
  const now = Date.now();
  const offset = Math.random() * daysAhead * 24 * 60 * 60 * 1000;
  return new Date(now + offset).toISOString();
}

// ---------------------------------------------------------------------------
// PROVINCE COORDINATES (Real data)
// ---------------------------------------------------------------------------

const PROVINCE_COORDS: Record<string, { lat: number; lng: number; districts: string[] }> = {
  "Hà Nội": {
    lat: 21.0285, lng: 105.8542,
    districts: ["Hoàn Kiếm", "Ba Đình", "Đống Đa", "Hai Bà Trưng", "Thanh Xuân", "Long Biên", "Cầu Giấy"],
  },
  "Hồ Chí Minh": {
    lat: 10.8231, lng: 106.6297,
    districts: ["Quận 1", "Quận 3", "Quận 7", "Bình Thạnh", "Thủ Đức", "Tân Bình", "Gò Vấp"],
  },
  "Đà Nẵng": {
    lat: 16.0748, lng: 108.223,
    districts: ["Hải Châu", "Thanh Khê", "Sơn Trà", "Ngũ Hành Sơn", "Liên Chiểu"],
  },
  "Huế": {
    lat: 16.4637, lng: 107.5909,
    districts: ["Thuận Hóa", "Phú Xuân", "Phong Điền", "Hương Thủy", "Hương Trà"],
  },
  "Cần Thơ": {
    lat: 10.0452, lng: 105.7469,
    districts: ["Ninh Kiều", "Bình Thủy", "Cái Răng", "Ô Môn", "Thốt Nốt"],
  },
  "Hải Phòng": {
    lat: 20.8449, lng: 106.6881,
    districts: ["Hồng Bàng", "Lê Chân", "Ngô Quyền", "Kiến An", "Hải An", "Đồ Sơn"],
  },
  "Nha Trang": {
    lat: 12.2388, lng: 109.1967,
    districts: ["Vĩnh Hải", "Vĩnh Phước", "Phương Sài", "Phương Sơn", "Tân Lập"],
  },
  "Đà Lạt": {
    lat: 11.9404, lng: 108.4583,
    districts: ["Phường 1", "Phường 2", "Phường 3", "Phường 4", "Phường 5"],
  },
  "Quảng Bình": {
    lat: 17.4689, lng: 106.6223,
    districts: ["Đồng Hới", "Ba Đồn", "Quảng Trạch", "Bố Trạch", "Quảng Ninh", "Lệ Thủy"],
  },
  "Quảng Nam": {
    lat: 15.8794, lng: 108.3353,
    districts: ["Tam Kỳ", "Hội An", "Đại Lộc", "Điện Bàn", "Duy Xuyên", "Thăng Bình"],
  },
  "Bến Tre": {
    lat: 10.2415, lng: 106.3759,
    districts: ["Bến Tre", "Châu Thành", "Chợ Lách", "Mỏ Cày Nam", "Giồng Trôm"],
  },
  "Trà Vinh": {
    lat: 9.9513, lng: 106.3346,
    districts: ["Trà Vinh", "Càng Long", "Cầu Kè", "Tiểu Cần", "Châu Thành"],
  },
  "Lào Cai": {
    lat: 22.338, lng: 103.8447,
    districts: ["Lào Cai", "Sa Pa", "Bảo Thắng", "Bảo Yên", "Bát Xát"],
  },
  "Yên Bái": {
    lat: 21.7229, lng: 104.8722,
    districts: ["Yên Bái", "Nghĩa Lộ", "Lục Yên", "Văn Yên", "Trấn Yên"],
  },
  "An Giang": {
    lat: 10.5216, lng: 105.1259,
    districts: ["Long Xuyên", "Châu Đốc", "Tân Châu", "Châu Phú", "Thoại Sơn"],
  },
};

// ---------------------------------------------------------------------------
// MOCK ALERTS (20 alerts - Real disaster events Vietnam)
// ---------------------------------------------------------------------------

export const MOCK_ALERTS: Alert[] = [
  // === EXTREME ALERTS (4) ===
  {
    id: generateId("ALT"),
    identifier: "VNDMA-2024-001-EXTREME",
    sender: "vndma",
    sent: "2024-10-15T06:00:00Z",
    status: "actual",
    msgType: "alert",
    scope: "public",
    info: {
      language: "vi",
      category: "met",
      event: "Bão số 5 đổ bộ",
      responseType: "evacuate",
      urgency: "immediate",
      severity: "extreme",
      certainty: "observed",
      headline: "CẢNH BÁO KHẨN CẤP: Bão số 5 đổ bộ Đà Nẵng - Quảng Nam",
      description: "Bão số 5 với sức gió cấp 14, giật cấp 17 đang đổ bộ vào khu vực Đà Nẵng - Quảng Nam. Dự kiến gây mưa rất to 300-500mm, sóng biển cao 5-7m. Nguy cơ lũ lụt, sạt lở đất nghiêm trọng. Yêu cầu người dân di tản ngay khỏi khu vực ven biển, vùng trũng thấp.",
      instruction: "1. Di tản ngay đến nơi trú ẩn an toàn\n2. Gia cố nhà cửa, neo buộc tàu thuyền\n3. Dự trữ nước uống, thực phẩm 3 ngày\n4. Tắt điện, khóa gas trước khi đi\n5. Mang theo giấy tờ quan trọng, thuốc men",
      area: {
        areaDesc: "Thành phố Đà Nẵng, Tỉnh Quảng Nam",
        provinces: ["Đà Nẵng", "Quảng Nam"],
        circle: { lat: 16.0748, lng: 108.223, radiusKm: 80 },
      },
      effective: "2024-10-15T06:00:00Z",
      expires: "2024-10-17T06:00:00Z",
      senderName: "Ban Chỉ đạo TW về PCTT",
    },
    delivery: {
      channels: ["push", "sms", "zalo", "loudspeaker"],
      deliveredCount: 245000,
      acknowledgedCount: 189000,
      failedCount: 12000,
      escalationLevel: 4,
    },
    createdAt: "2024-10-15T06:00:00Z",
    updatedAt: "2024-10-15T12:00:00Z",
  },
  {
    id: generateId("ALT"),
    identifier: "VNDMA-2024-002-EXTREME",
    sender: "vndma",
    sent: "2024-10-15T08:30:00Z",
    status: "actual",
    msgType: "alert",
    scope: "public",
    info: {
      language: "vi",
      category: "geo",
      event: "Lũ lụt nghiêm trọng",
      responseType: "evacuate",
      urgency: "immediate",
      severity: "extreme",
      certainty: "observed",
      headline: "LŨ LỤT NGHIÊM TRỌNG: Quảng Bình - Mưa 400mm/24h",
      description: "Mưa lớn kéo dài 48h liên tục, tổng lượng mưa 400-600mm. Mực nước sông Gianh dâng vượt mức báo động cấp 3. Nhiều xã bị ngập sâu 2-3m, giao thông tê liệt hoàn toàn. Đã có 12 người chết, 45 người mất tích. Cần cứu hộ khẩn cấp.",
      instruction: "1. Di chuyển ngay lên vùng cao\n2. Không cố lái xe qua vùng ngập\n3. Nếu bị kẹt, lên mái nhà chờ cứu hộ\n4. Gọi 114 hoặc 115 để được cứu\n5. Không uống nước ngập",
      area: {
        areaDesc: "Tỉnh Quảng Bình - Khu vực ven sông Gianh",
        provinces: ["Quảng Bình"],
        circle: { lat: 17.4689, lng: 106.6223, radiusKm: 60 },
      },
      effective: "2024-10-15T08:30:00Z",
      expires: "2024-10-18T08:30:00Z",
      senderName: "Ban Chỉ đạo TW về PCTT",
    },
    delivery: {
      channels: ["push", "sms", "zalo", "loudspeaker"],
      deliveredCount: 125000,
      acknowledgedCount: 98000,
      failedCount: 8000,
      escalationLevel: 4,
    },
    createdAt: "2024-10-15T08:30:00Z",
    updatedAt: "2024-10-15T14:00:00Z",
  },
  {
    id: generateId("ALT"),
    identifier: "CNET-AI-2024-003-EXTREME",
    sender: "cnet-ai",
    sent: "2024-09-20T14:00:00Z",
    status: "actual",
    msgType: "alert",
    scope: "public",
    info: {
      language: "vi",
      category: "geo",
      event: "Sạt lở đất nghiêm trọng",
      responseType: "evacuate",
      urgency: "immediate",
      severity: "extreme",
      certainty: "observed",
      headline: "KHẨN CẤP: Sạt lở đất nghiêm trọng tại Lào Cai - Nhiều người mắc kẹt",
      description: "Mưa lớn 300mm/48h gây sạt lở đất nghiêm trọng tại Sa Pa, Lào Cai. Khối lượng đất đá hàng nghìn mét khối trùm lên nhà dân. Đã có 8 người chết, 23 người mất tích. Đường quốc lộ 4D bị chia cắt. Lực lượng cứu hộ đang tiếp cận.",
      instruction: "1. Di tản ngay khỏi khu vực sườn đồi\n2. Không đến gần khu vực sạt lở\n3. Nếu nghe tiếng đất nứt, chạy ngay\n4. Gọi 114 để báo cáo vị trí\n5. Theo dõi cập nhật từ chính quyền",
      area: {
        areaDesc: "Huyện Sa Pa, Tỉnh Lào Cai",
        provinces: ["Lào Cai"],
        circle: { lat: 22.338, lng: 103.8447, radiusKm: 40 },
      },
      effective: "2024-09-20T14:00:00Z",
      expires: "2024-09-23T14:00:00Z",
      senderName: "AI CuuNet",
    },
    delivery: {
      channels: ["push", "sms"],
      deliveredCount: 45000,
      acknowledgedCount: 32000,
      failedCount: 3000,
      escalatedAt: "2024-09-20T14:10:00Z",
      escalationLevel: 2,
    },
    createdAt: "2024-09-20T14:00:00Z",
    updatedAt: "2024-09-20T18:00:00Z",
  },
  {
    id: generateId("ALT"),
    identifier: "VNDMA-2024-004-EXTREME",
    sender: "vndma",
    sent: "2024-10-28T03:00:00Z",
    status: "actual",
    msgType: "alert",
    scope: "public",
    info: {
      language: "vi",
      category: "met",
      event: "Bão số 9 đổ bộ",
      responseType: "evacuate",
      urgency: "immediate",
      severity: "extreme",
      certainty: "likely",
      headline: "CẢNH BÁO CỰC ĐỘNG: Bão số 9 cấp 16 đổ bộ Huế - Đà Nẵng",
      description: "Bão số 9, cấp 16 giật cấp 17+, áp thấp tâm bão 950hPa. Sóng biển cao 8-10m. Mưa 500-700mm. Đây là cơn bão mạnh nhất 30 năm qua. Yêu cầu di tản toàn bộ khu vực ven biển 5km.",
      instruction: "DI TẢN NGAY. Không ở lại nhà ven biển. Mang theo CCCD, thuốc men, nước uống. Đến nơi trú ẩn cao hơn 10m so với mực nước biển.",
      area: {
        areaDesc: "Thừa Thiên Huế, Đà Nẵng, Quảng Nam",
        provinces: ["Huế", "Đà Nẵng", "Quảng Nam"],
        circle: { lat: 16.2, lng: 108.0, radiusKm: 120 },
      },
      effective: "2024-10-28T03:00:00Z",
      expires: "2024-10-30T03:00:00Z",
      senderName: "Ban Chỉ đạo TW về PCTT",
    },
    delivery: {
      channels: ["push", "sms", "zalo", "loudspeaker"],
      deliveredCount: 520000,
      acknowledgedCount: 410000,
      failedCount: 25000,
      escalationLevel: 4,
    },
    createdAt: "2024-10-28T03:00:00Z",
    updatedAt: "2024-10-28T06:00:00Z",
  },

  // === SEVERE ALERTS (6) ===
  {
    id: generateId("ALT"),
    identifier: "VNDMA-2024-005-SEVERE",
    sender: "vndma",
    sent: "2024-10-14T10:00:00Z",
    status: "actual",
    msgType: "alert",
    scope: "public",
    info: {
      language: "vi",
      category: "geo",
      event: "Sạt lở đất",
      responseType: "prepare",
      urgency: "expected",
      severity: "severe",
      certainty: "likely",
      headline: "CẢNH BÁO: Sạt lở đất tại Yên Bái - Di chuyển khỏi sườn đồi",
      description: "Mưa lớn 200mm/24h tại Yên Bái. Nguy cơ sạt lở đất cao tại các huyện miền núi. Đã ghi nhận 3 điểm sạt lở nhỏ. Chính quyền yêu cầu di tản phòng ngừa.",
      instruction: "1. Di chuyển khỏi khu vực sườn đồi\n2. Không ở dưới chân taluy\n3. Chuẩn bị đồ sơ tán\n4. Theo dõi loa phát thanh xã",
      area: {
        areaDesc: "Tỉnh Yên Bái - Khu vực miền núi",
        provinces: ["Yên Bái"],
        circle: { lat: 21.7229, lng: 104.8722, radiusKm: 50 },
      },
      effective: "2024-10-14T10:00:00Z",
      expires: "2024-10-16T10:00:00Z",
      senderName: "Ban Chỉ đạo TW về PCTT",
    },
    delivery: {
      channels: ["push", "sms", "zalo"],
      deliveredCount: 67000,
      acknowledgedCount: 45000,
      failedCount: 4000,
      escalationLevel: 3,
    },
    createdAt: "2024-10-14T10:00:00Z",
    updatedAt: "2024-10-14T16:00:00Z",
  },
  {
    id: generateId("ALT"),
    identifier: "VNDMA-2024-006-SEVERE",
    sender: "vndma",
    sent: "2024-10-14T15:00:00Z",
    status: "actual",
    msgType: "alert",
    scope: "public",
    info: {
      language: "vi",
      category: "met",
      event: "Mưa lớn cảnh báo",
      responseType: "prepare",
      urgency: "expected",
      severity: "severe",
      certainty: "likely",
      headline: "MƯA LỚN: Huế - Dự kiến 250mm trong 24h tới",
      description: "Rãnh áp thấp kết hợp không khí lạnh gây mưa rất to cho Thừa Thiên Huế. Dự kiến 200-300mm/24h. Nguy cơ ngập lụt diện rộng tại vùng trũng. Sông Hương có thể dâng vượt báo động cấp 2.",
      instruction: "1. Dự trữ nước uống, thực phẩm\n2. Nâng đồ lên cao\n3. Chuẩn bị đèn pin, sạc dự phòng\n4. Không ra ngoài khi mưa to",
      area: {
        areaDesc: "Thừa Thiên Huế",
        provinces: ["Huế"],
        circle: { lat: 16.4637, lng: 107.5909, radiusKm: 45 },
      },
      effective: "2024-10-14T15:00:00Z",
      expires: "2024-10-16T15:00:00Z",
      senderName: "Ban Chỉ đạo TW về PCTT",
    },
    delivery: {
      channels: ["push", "sms"],
      deliveredCount: 89000,
      acknowledgedCount: 67000,
      failedCount: 5000,
      escalationLevel: 2,
    },
    createdAt: "2024-10-14T15:00:00Z",
    updatedAt: "2024-10-14T20:00:00Z",
  },
  {
    id: generateId("ALT"),
    identifier: "CNET-AI-2024-007-SEVERE",
    sender: "cnet-ai",
    sent: "2024-03-15T08:00:00Z",
    status: "actual",
    msgType: "alert",
    scope: "public",
    info: {
      language: "vi",
      category: "met",
      event: "Hạn hán nghiêm trọng",
      responseType: "prepare",
      urgency: "expected",
      severity: "severe",
      certainty: "observed",
      headline: "HẠN HÁN NGHIÊM TRỌNG: Cần Thơ, An Giang - Xâm nhập mặn sâu",
      description: "Hạn hán kéo dài 3 tháng, xâm nhập mặn sâu vào nội đồng. Độ mặn vượt 4‰ tại nhiều trạm. Hồ chứa nước chỉ còn 15% dung tích. 50,000 hecta lúa bị thiệt hại. Nước sinh hoạt khan hiếm.",
      instruction: "1. Tiết kiệm nước tối đa\n2. Dự trữ nước mưa\n3. Không tưới nước lãng phí\n4. Sử dụng hệ thống lọc nước\n5. Báo cáo thiệt hại cho xã",
      area: {
        areaDesc: "Đồng bằng sông Cửu Long",
        provinces: ["Cần Thơ", "An Giang", "Bến Tre", "Trà Vinh"],
        circle: { lat: 10.2, lng: 105.5, radiusKm: 100 },
      },
      effective: "2024-03-15T08:00:00Z",
      expires: "2024-04-15T08:00:00Z",
      senderName: "AI CuuNet",
    },
    delivery: {
      channels: ["push"],
      deliveredCount: 156000,
      acknowledgedCount: 98000,
      failedCount: 10000,
      escalationLevel: 1,
    },
    createdAt: "2024-03-15T08:00:00Z",
    updatedAt: "2024-03-15T12:00:00Z",
  },
  {
    id: generateId("ALT"),
    identifier: "INTL-2024-008-SEVERE",
    sender: "international",
    sent: "2024-08-10T02:00:00Z",
    status: "actual",
    msgType: "alert",
    scope: "public",
    info: {
      language: "vi",
      category: "geo",
      event: "Động đất",
      responseType: "monitor",
      urgency: "immediate",
      severity: "severe",
      certainty: "observed",
      headline: "ĐỘNG ĐẤT 5.2 SR: Nha Trang - Run chấn lan rộng",
      description: "Động đất magnitude 5.2 xảy ra lúc 9:00 sáng, tâm chấn cách Nha Trang 45km về phía Đông. Run chấn cảm nhận rõ tại Khánh Hòa, Phú Yên, Bình Định. Chưa có cảnh báo sóng thần. Kiểm tra nhà cửa trước khi vào.",
      instruction: "1. Kiểm tra vết nứt nhà cửa\n2. Không vào tòa nhà hư hại\n3. Chuẩn bị cho dư chấn\n4. Theo dõi cập nhật từ BMKG",
      area: {
        areaDesc: "Khánh Hòa và vùng lân cận",
        provinces: ["Nha Trang"],
        circle: { lat: 12.2388, lng: 109.1967, radiusKm: 70 },
      },
      effective: "2024-08-10T02:00:00Z",
      expires: "2024-08-12T02:00:00Z",
      senderName: "USGS / GDACS",
    },
    delivery: {
      channels: ["push", "sms"],
      deliveredCount: 134000,
      acknowledgedCount: 89000,
      failedCount: 7000,
      escalationLevel: 2,
    },
    createdAt: "2024-08-10T02:00:00Z",
    updatedAt: "2024-08-10T06:00:00Z",
  },
  {
    id: generateId("ALT"),
    identifier: "VNDMA-2024-009-SEVERE",
    sender: "vndma",
    sent: "2024-09-05T11:00:00Z",
    status: "actual",
    msgType: "alert",
    scope: "public",
    info: {
      language: "vi",
      category: "met",
      event: "Giông lốc mạnh",
      responseType: "shelter",
      urgency: "immediate",
      severity: "severe",
      certainty: "observed",
      headline: "GIÔNG LỐC MẠNH: Hải Phòng - Giật cấp 10, tốc mái nhà",
      description: "Giông lốc kèm mưa lớn xảy ra tại Hải Phòng. Gió giật cấp 10, nhiều cây cối gãy đổ. Đã có 3 người bị thương do mái tôn bay. Mất điện diện rộng. Ước tính 200 nhà bị hư hại.",
      instruction: "1. Ở trong nhà, đóng kín cửa\n2. Tránh xa cửa kính\n3. Không trú dưới cây\n4. Báo cáo thiệt hại qua app",
      area: {
        areaDesc: "Thành phố Hải Phòng",
        provinces: ["Hải Phòng"],
        circle: { lat: 20.8449, lng: 106.6881, radiusKm: 35 },
      },
      effective: "2024-09-05T11:00:00Z",
      expires: "2024-09-06T11:00:00Z",
      senderName: "Ban Chỉ đạo TW về PCTT",
    },
    delivery: {
      channels: ["push", "sms", "zalo"],
      deliveredCount: 78000,
      acknowledgedCount: 56000,
      failedCount: 4000,
      escalationLevel: 2,
    },
    createdAt: "2024-09-05T11:00:00Z",
    updatedAt: "2024-09-05T14:00:00Z",
  },
  {
    id: generateId("ALT"),
    identifier: "VNDMA-2024-010-SEVERE",
    sender: "vndma",
    sent: "2024-10-20T09:00:00Z",
    status: "actual",
    msgType: "update",
    scope: "public",
    info: {
      language: "vi",
      category: "met",
      event: "Triều cường cao",
      responseType: "prepare",
      urgency: "expected",
      severity: "severe",
      certainty: "likely",
      headline: "TRIỀU CƯỜNG: Hồ Chí Minh - Mực nước dâng 1.7m, ngập diện rộng",
      description: "Triều cường kết hợp mưa lớn gây ngập nặng tại TP.HCM. Quận 7, Bình Thạnh, Thủ Đức ngập sâu 0.5-1m. Nhiều tuyến đường không thể lưu thông. Dự kiến đỉnh triều chiều nay.",
      instruction: "1. Hạn chế ra ngoài\n2. Không lái xe qua vùng ngập\n3. Nâng xe lên cao\n4. Theo dõi mực nước trực tuyến",
      area: {
        areaDesc: "TP. Hồ Chí Minh - Quận ven sông",
        provinces: ["Hồ Chí Minh"],
        circle: { lat: 10.8231, lng: 106.6297, radiusKm: 30 },
      },
      effective: "2024-10-20T09:00:00Z",
      expires: "2024-10-21T09:00:00Z",
      senderName: "Ban Chỉ đạo TW về PCTT",
    },
    delivery: {
      channels: ["push", "zalo"],
      deliveredCount: 312000,
      acknowledgedCount: 210000,
      failedCount: 15000,
      escalationLevel: 2,
    },
    createdAt: "2024-10-20T09:00:00Z",
    updatedAt: "2024-10-20T15:00:00Z",
  },

  // === MODERATE ALERTS (6) ===
  {
    id: generateId("ALT"),
    identifier: "CNET-AI-2024-011-MOD",
    sender: "cnet-ai",
    sent: "2024-10-14T07:00:00Z",
    status: "actual",
    msgType: "alert",
    scope: "public",
    info: {
      language: "vi",
      category: "met",
      event: "Mưa vừa đến mưa to",
      responseType: "monitor",
      urgency: "expected",
      severity: "moderate",
      certainty: "likely",
      headline: "MƯA VỪA ĐẾN MƯA TO: Hà Nội - Dự kiến 80-120mm",
      description: "Không khí lạnh tràn về kết hợp ẩm từ biển gây mưa vừa đến mưa to cho Hà Nội. Dự kiến 80-120mm trong 12h. Có thể ngập úng cục bộ tại một số tuyến phố.",
      instruction: "1. Mang theo áo mưa\n2. Hạn chế di chuyển\n3. Tránh khu vực hay ngập",
      area: {
        areaDesc: "Thủ đô Hà Nội",
        provinces: ["Hà Nội"],
        circle: { lat: 21.0285, lng: 105.8542, radiusKm: 25 },
      },
      effective: "2024-10-14T07:00:00Z",
      expires: "2024-10-15T07:00:00Z",
      senderName: "AI CuuNet",
    },
    delivery: {
      channels: ["push"],
      deliveredCount: 450000,
      acknowledgedCount: 280000,
      failedCount: 20000,
      escalationLevel: 1,
    },
    createdAt: "2024-10-14T07:00:00Z",
    updatedAt: "2024-10-14T12:00:00Z",
  },
  {
    id: generateId("ALT"),
    identifier: "CNET-AI-2024-012-MOD",
    sender: "cnet-ai",
    sent: "2024-10-10T14:00:00Z",
    status: "actual",
    msgType: "alert",
    scope: "public",
    info: {
      language: "vi",
      category: "met",
      event: "Nắng nóng gay gắt",
      responseType: "avoid",
      urgency: "expected",
      severity: "moderate",
      certainty: "likely",
      headline: "NẮNG NÓNG: Hồ Chí Minh - Nhiệt độ 39°C, chỉ số UV cao",
      description: "Nắng nóng gay gắt trên diện rộng. Nhiệt độ cao nhất 38-40°C. Chỉ số UV đạt mức 10-11 (rất cao). Nguy cơ say nắng, cháy rừng. Khuyến cáo hạn chế ra ngoài 10h-15h.",
      instruction: "1. Uống nhiều nước\n2. Hạn chế ra ngoài 10h-15h\n3. Mặc áo chống nắng\n4. Không để trẻ em trong xe đóng kín",
      area: {
        areaDesc: "TP. Hồ Chí Minh và vùng phụ cận",
        provinces: ["Hồ Chí Minh"],
        circle: { lat: 10.8231, lng: 106.6297, radiusKm: 40 },
      },
      effective: "2024-10-10T14:00:00Z",
      expires: "2024-10-12T14:00:00Z",
      senderName: "AI CuuNet",
    },
    delivery: {
      channels: ["push"],
      deliveredCount: 380000,
      acknowledgedCount: 220000,
      failedCount: 18000,
      escalationLevel: 1,
    },
    createdAt: "2024-10-10T14:00:00Z",
    updatedAt: "2024-10-10T18:00:00Z",
  },
  {
    id: generateId("ALT"),
    identifier: "VNDMA-2024-013-MOD",
    sender: "vndma",
    sent: "2024-10-12T16:00:00Z",
    status: "actual",
    msgType: "alert",
    scope: "public",
    info: {
      language: "vi",
      category: "met",
      event: "Áp thấp nhiệt đới",
      responseType: "monitor",
      urgency: "future",
      severity: "moderate",
      certainty: "possible",
      headline: "ÁP THẤP NHIỆT ĐỚI: Biển Đông - Có thể mạnh lên thành bão",
      description: "Áp thấp nhiệt đới trên Biển Đông đang di chuyển theo hướng Tây Tây Bắc. Có thể mạnh lên thành bão trong 48h tới. Dự ảnh hưởng đến các tỉnh miền Trung.",
      instruction: "1. Theo dõi bản tin thời tiết\n2. Chuẩn bị phương án phòng chống\n3. Kiểm tra gia cố nhà cửa",
      area: {
        areaDesc: "Biển Đông - Ảnh hưởng các tỉnh miền Trung",
        provinces: ["Đà Nẵng", "Quảng Nam", "Huế"],
        circle: { lat: 15.0, lng: 110.0, radiusKm: 200 },
      },
      effective: "2024-10-12T16:00:00Z",
      expires: "2024-10-15T16:00:00Z",
      senderName: "Ban Chỉ đạo TW về PCTT",
    },
    delivery: {
      channels: ["push"],
      deliveredCount: 210000,
      acknowledgedCount: 145000,
      failedCount: 10000,
      escalationLevel: 1,
    },
    createdAt: "2024-10-12T16:00:00Z",
    updatedAt: "2024-10-13T08:00:00Z",
  },
  {
    id: generateId("ALT"),
    identifier: "CNET-AI-2024-014-MOD",
    sender: "cnet-ai",
    sent: "2024-04-05T10:00:00Z",
    status: "actual",
    msgType: "alert",
    scope: "public",
    info: {
      language: "vi",
      category: "met",
      event: "Xâm nhập mặn",
      responseType: "prepare",
      urgency: "expected",
      severity: "moderate",
      certainty: "observed",
      headline: "XÂM NHẬP MẶN: Bến Tre - Độ mặn vượt 2‰",
      description: "Xâm nhập mặn tiếp tục sâu vào nội đồng Bến Tre. Độ mặn vượt 2‰ tại nhiều trạm đo. Ảnh hưởng đến vườn cây ăn trái và nước sinh hoạt. Dự kiến kéo dài 2 tuần.",
      instruction: "1. Dự trữ nước ngọt\n2. Không tưới cây bằng nước mặn\n3. Sử dụng hệ thống lọc\n4. Báo cáo thiệt hại",
      area: {
        areaDesc: "Tỉnh Bến Tre",
        provinces: ["Bến Tre"],
        circle: { lat: 10.2415, lng: 106.3759, radiusKm: 40 },
      },
      effective: "2024-04-05T10:00:00Z",
      expires: "2024-04-20T10:00:00Z",
      senderName: "AI CuuNet",
    },
    delivery: {
      channels: ["push"],
      deliveredCount: 56000,
      acknowledgedCount: 34000,
      failedCount: 3000,
      escalationLevel: 1,
    },
    createdAt: "2024-04-05T10:00:00Z",
    updatedAt: "2024-04-05T14:00:00Z",
  },
  {
    id: generateId("ALT"),
    identifier: "COMM-2024-015-MOD",
    sender: "community",
    sent: "2024-10-13T18:00:00Z",
    status: "actual",
    msgType: "alert",
    scope: "public",
    info: {
      language: "vi",
      category: "safety",
      event: "Ngập đường phố",
      responseType: "avoid",
      urgency: "immediate",
      severity: "moderate",
      certainty: "observed",
      headline: "NGẬP ĐƯỜNG: Đà Nẵng - Nhiều tuyến phố ngập 0.3-0.5m",
      description: "Mưa lớn 2h liên tục gây ngập nhiều tuyến phố Đà Nẵng. Các tuyến Nguyễn Văn Linh, Lê Duẩn, Điện Biên Phủ ngập 0.3-0.5m. Giao thông ùn tắc. Xe máy không nên di chuyển.",
      instruction: "1. Tránh các tuyến đường ngập\n2. Không lái xe máy qua vùng ngập\n3. Chọn đường thay thế",
      area: {
        areaDesc: "Trung tâm Đà Nẵng",
        provinces: ["Đà Nẵng"],
        circle: { lat: 16.0748, lng: 108.223, radiusKm: 15 },
      },
      effective: "2024-10-13T18:00:00Z",
      expires: "2024-10-14T06:00:00Z",
      senderName: "Cộng đồng CuuNet",
    },
    delivery: {
      channels: ["push"],
      deliveredCount: 23000,
      acknowledgedCount: 15000,
      failedCount: 1000,
      escalationLevel: 1,
    },
    createdAt: "2024-10-13T18:00:00Z",
    updatedAt: "2024-10-13T20:00:00Z",
  },
  {
    id: generateId("ALT"),
    identifier: "CNET-AI-2024-016-MOD",
    sender: "cnet-ai",
    sent: "2024-10-25T11:00:00Z",
    status: "actual",
    msgType: "alert",
    scope: "public",
    info: {
      language: "vi",
      category: "geo",
      event: "Sạt lở đất nhẹ",
      responseType: "monitor",
      urgency: "expected",
      severity: "moderate",
      certainty: "possible",
      headline: "CẢNH BÁO SẠT LỞ: Đà Lạt - Taluy có dấu hiệu nứt",
      description: "Phát hiện vết nứt tại taluy âm đường đèo Prenn, Đà Lạt. Mưa lớn có thể gây sạt lở. Khuyến cáo hạn chế di chuyển qua khu vực này.",
      instruction: "1. Tránh đường đèo Prenn\n2. Chọn đường thay thế\n3. Theo dõi cập nhật",
      area: {
        areaDesc: "Đường đèo Prenn, Đà Lạt",
        provinces: ["Đà Lạt"],
        circle: { lat: 11.9404, lng: 108.4583, radiusKm: 15 },
      },
      effective: "2024-10-25T11:00:00Z",
      expires: "2024-10-27T11:00:00Z",
      senderName: "AI CuuNet",
    },
    delivery: {
      channels: ["push"],
      deliveredCount: 18000,
      acknowledgedCount: 12000,
      failedCount: 800,
      escalationLevel: 1,
    },
    createdAt: "2024-10-25T11:00:00Z",
    updatedAt: "2024-10-25T15:00:00Z",
  },

  // === MINOR ALERTS (4) ===
  {
    id: generateId("ALT"),
    identifier: "CNET-AI-2024-017-MIN",
    sender: "cnet-ai",
    sent: "2024-10-22T08:00:00Z",
    status: "actual",
    msgType: "alert",
    scope: "public",
    info: {
      language: "vi",
      category: "met",
      event: "Mưa nhỏ",
      responseType: "monitor",
      urgency: "future",
      severity: "minor",
      certainty: "likely",
      headline: "MƯA NHỎ: Hà Nội - Dự kiến 20-40mm trong 12h",
      description: "Mưa nhỏ rải rác tại Hà Nội. Lượng mưa 20-40mm. Không có nguy cơ ngập lụt. Giao thông bình thường.",
      instruction: "Mang theo ô khi ra ngoài.",
      area: {
        areaDesc: "Hà Nội",
        provinces: ["Hà Nội"],
        circle: { lat: 21.0285, lng: 105.8542, radiusKm: 20 },
      },
      effective: "2024-10-22T08:00:00Z",
      expires: "2024-10-23T08:00:00Z",
      senderName: "AI CuuNet",
    },
    delivery: {
      channels: ["push"],
      deliveredCount: 120000,
      acknowledgedCount: 75000,
      failedCount: 5000,
      escalationLevel: 1,
    },
    createdAt: "2024-10-22T08:00:00Z",
    updatedAt: "2024-10-22T10:00:00Z",
  },
  {
    id: generateId("ALT"),
    identifier: "CNET-AI-2024-018-MIN",
    sender: "cnet-ai",
    sent: "2024-10-18T12:00:00Z",
    status: "actual",
    msgType: "alert",
    scope: "public",
    info: {
      language: "vi",
      category: "met",
      event: "Gió mạnh",
      responseType: "monitor",
      urgency: "future",
      severity: "minor",
      certainty: "possible",
      headline: "Gió MẠNH: Hải Phòng - Gió cấp 6-7 trên biển",
      description: "Gió mạnh cấp 6-7 trên vùng biển Hải Phòng. Khuyến cáo tàu thuyền nhỏ không ra khơi. Ảnh hưởng nhẹ đến giao thông đường thủy.",
      instruction: "Tàu thuyền nhỏ hạn chế ra khơi.",
      area: {
        areaDesc: "Vùng biển Hải Phòng",
        provinces: ["Hải Phòng"],
        circle: { lat: 20.8449, lng: 106.6881, radiusKm: 50 },
      },
      effective: "2024-10-18T12:00:00Z",
      expires: "2024-10-19T12:00:00Z",
      senderName: "AI CuuNet",
    },
    delivery: {
      channels: ["push"],
      deliveredCount: 34000,
      acknowledgedCount: 21000,
      failedCount: 2000,
      escalationLevel: 1,
    },
    createdAt: "2024-10-18T12:00:00Z",
    updatedAt: "2024-10-18T14:00:00Z",
  },
  {
    id: generateId("ALT"),
    identifier: "CNET-AI-2024-019-MIN",
    sender: "cnet-ai",
    sent: "2024-04-10T09:00:00Z",
    status: "actual",
    msgType: "alert",
    scope: "public",
    info: {
      language: "vi",
      category: "met",
      event: "Sương mù",
      responseType: "monitor",
      urgency: "future",
      severity: "minor",
      certainty: "observed",
      headline: "SƯƠNG MÙ: Đà Lạt - Tầm nhìn dưới 200m",
      description: "Sương mù dày đặc tại Đà Lạt. Tầm nhìn dưới 200m. Ảnh hưởng đến giao thông đường bộ. Lái xe cẩn thận.",
      instruction: "Bật đèn xe, giảm tốc độ, giữ khoảng cách an toàn.",
      area: {
        areaDesc: "Đà Lạt và vùng phụ cận",
        provinces: ["Đà Lạt"],
        circle: { lat: 11.9404, lng: 108.4583, radiusKm: 20 },
      },
      effective: "2024-04-10T09:00:00Z",
      expires: "2024-04-10T18:00:00Z",
      senderName: "AI CuuNet",
    },
    delivery: {
      channels: ["push"],
      deliveredCount: 12000,
      acknowledgedCount: 8000,
      failedCount: 500,
      escalationLevel: 1,
    },
    createdAt: "2024-04-10T09:00:00Z",
    updatedAt: "2024-04-10T10:00:00Z",
  },
  {
    id: generateId("ALT"),
    identifier: "CNET-AI-2024-020-MIN",
    sender: "cnet-ai",
    sent: "2024-10-08T15:00:00Z",
    status: "actual",
    msgType: "alert",
    scope: "public",
    info: {
      language: "vi",
      category: "met",
      event: "Nhiệt độ giảm",
      responseType: "monitor",
      urgency: "future",
      severity: "minor",
      certainty: "likely",
      headline: "LẠNH: Hà Nội - Nhiệt độ giảm xuống 18°C",
      description: "Không khí lạnh tràn về, nhiệt độ Hà Nội giảm xuống 18°C. Dự kiến duy trì 2-3 ngày. Khuyến cáo mặc ấm.",
      instruction: "Mặc ấm, đặc biệt cho người già và trẻ em.",
      area: {
        areaDesc: "Hà Nội và các tỉnh phía Bắc",
        provinces: ["Hà Nội"],
        circle: { lat: 21.0285, lng: 105.8542, radiusKm: 60 },
      },
      effective: "2024-10-08T15:00:00Z",
      expires: "2024-10-11T15:00:00Z",
      senderName: "AI CuuNet",
    },
    delivery: {
      channels: ["push"],
      deliveredCount: 95000,
      acknowledgedCount: 60000,
      failedCount: 4000,
      escalationLevel: 1,
    },
    createdAt: "2024-10-08T15:00:00Z",
    updatedAt: "2024-10-08T16:00:00Z",
  },
];

// ---------------------------------------------------------------------------
// MOCK SOS REQUESTS (30 requests across 15 provinces)
// ---------------------------------------------------------------------------

function createSOSRequest(
  type: SOSType,
  severity: SOSEmergencyLevel,
  status: SOSStatus,
  province: string,
  daysAgo: number,
  peopleCount: number,
  hasChildren: boolean,
  hasElderly: boolean,
  isOffline: boolean,
  description: string,
): SOSRequest {
  const coords = PROVINCE_COORDS[province];
  const lat = coords.lat + (Math.random() - 0.5) * 0.1;
  const lng = coords.lng + (Math.random() - 0.5) * 0.1;
  const district = coords.districts[Math.floor(Math.random() * coords.districts.length)];
  const createdAt = randomPastDate(daysAgo);

  const timeline: SOSTimeline[] = [
    { status: "sent", timestamp: createdAt, note: "SOS được gửi" },
  ];

  if (status !== "queued" && status !== "sent") {
    timeline.push({ status: "delivered", timestamp: new Date(new Date(createdAt).getTime() + 30000).toISOString(), note: "Hệ thống đã nhận" });
  }
  if (["acknowledged", "dispatched", "resolved"].includes(status)) {
    timeline.push({ status: "acknowledged", timestamp: new Date(new Date(createdAt).getTime() + 120000).toISOString(), note: "Đội cứu hộ xác nhận", updatedBy: "Đội PCTT " + province });
  }
  if (["dispatched", "resolved"].includes(status)) {
    timeline.push({ status: "dispatched", timestamp: new Date(new Date(createdAt).getTime() + 300000).toISOString(), note: "Đội cứu hộ đang trên đường", updatedBy: "Đội PCTT " + province });
  }
  if (status === "resolved") {
    timeline.push({ status: "resolved", timestamp: new Date(new Date(createdAt).getTime() + 1800000).toISOString(), note: "Đã giải quyết", updatedBy: "Đội PCTT " + province });
  }

  const priorityBase = severity === "life_threatening" ? 100 : severity === "urgent" ? 70 : 40;
  const priorityScore = priorityBase + (hasChildren ? 10 : 0) + (hasElderly ? 10 : 0) + peopleCount * 2;

  return {
    id: generateId("SOS"),
    userId: generateId("USR"),
    location: {
      lat,
      lng,
      accuracy: Math.floor(Math.random() * 50) + 5,
      address: `${district}, ${province}`,
      province,
      district,
    },
    situation: {
      type,
      severity,
      peopleCount,
      description,
      hasChildren,
      hasElderly,
      hasDisabled: Math.random() > 0.8,
      isTrapped: type === "trapped" || Math.random() > 0.7,
      needsMedical: severity === "life_threatening" || Math.random() > 0.6,
    },
    contact: {
      name: `Người dùng ${Math.floor(Math.random() * 1000)}`,
      phone: `09${Math.floor(Math.random() * 100000000).toString().padStart(8, "0")}`,
    },
    status,
    timeline,
    createdAt,
    sentAt: status !== "queued" ? createdAt : undefined,
    deliveredAt: ["delivered", "acknowledged", "dispatched", "resolved"].includes(status) ? new Date(new Date(createdAt).getTime() + 30000).toISOString() : undefined,
    acknowledgedAt: ["acknowledged", "dispatched", "resolved"].includes(status) ? new Date(new Date(createdAt).getTime() + 120000).toISOString() : undefined,
    dispatchedAt: ["dispatched", "resolved"].includes(status) ? new Date(new Date(createdAt).getTime() + 300000).toISOString() : undefined,
    resolvedAt: status === "resolved" ? new Date(new Date(createdAt).getTime() + 1800000).toISOString() : undefined,
    isOffline,
    retryCount: isOffline ? Math.floor(Math.random() * 3) : 0,
    maxRetries: 10,
    priorityScore,
    estimatedResponseTime: Math.floor(Math.random() * 30) + 10,
    assignedTeam: status !== "queued" && status !== "sent" ? `Đội PCTT ${province}` : undefined,
  };
}

export const MOCK_SOS_REQUESTS: SOSRequest[] = [
  // === LIFE-THREATENING (10) ===
  createSOSRequest("flood", "life_threatening", "dispatched", "Quảng Bình", 0.5, 4, true, true, false, "Gia đình 4 người bị kẹt trong nhà, nước ngập lên 1.5m. Có trẻ em 3 tuổi và bà cụ 75 tuổi. Cần cứu hộ ngay."),
  createSOSRequest("landslide", "life_threatening", "resolved", "Lào Cai", 2, 6, true, false, false, "Sạt lở đất vùi lấp một phần nhà. 6 người trong nhà, 2 người bị thương nặng. Đội cứu hộ đã đến."),
  createSOSRequest("storm", "life_threatening", "acknowledged", "Đà Nẵng", 0.3, 3, false, true, false, "Mái nhà bị tốc hoàn toàn, 3 người bị thương do mảnh vỡ. Bà cụ bị gãy chân. Cần cấp cứu."),
  createSOSRequest("fire", "life_threatening", "dispatched", "Hồ Chí Minh", 0.1, 8, true, false, false, "Cháy lớn tại chung cư tầng 5. 8 người mắc kẹt, khói dày đặc. Cầu thang bị chặn. Cần xe thang cứu hộ."),
  createSOSRequest("medical", "life_threatening", "delivered", "Hà Nội", 0.2, 1, false, false, false, "Người cao tuổi bị đột quỵ, mất ý thức. Không thể di chuyển. Cần cấp cứu ngay."),
  createSOSRequest("tsunami", "life_threatening", "resolved", "Nha Trang", 5, 12, true, true, false, "Sóng thần nhỏ ập vào bờ. 12 người bị cuốn, 4 người mất tích. Lực lượng cứu hộ đang tìm kiếm."),
  createSOSRequest("trapped", "life_threatening", "acknowledged", "Yên Bái", 0.4, 5, true, true, false, "5 người bị mắc kẹt trong nhà do sạt lở đất chặn đường. Có trẻ em và người già. Không thể tự thoát."),
  createSOSRequest("flood", "life_threatening", "sent", "Quảng Nam", 0.6, 3, false, true, true, "Nước lũ dâng nhanh, 3 người leo lên mái nhà. Mạng yếu, SOS gửi offline."),
  createSOSRequest("earthquake", "life_threatening", "dispatched", "Nha Trang", 1, 2, false, false, false, "Động đất làm sập một bức tường. 2 người bị vùi lấp dưới đống đổ nát."),
  createSOSRequest("medical", "life_threatening", "resolved", "Huế", 3, 1, false, false, false, "Trẻ em 5 tuổi bị đuối nước, đã sơ cứu nhưng cần đưa đến bệnh viện ngay."),

  // === URGENT (12) ===
  createSOSRequest("flood", "urgent", "dispatched", "An Giang", 0.8, 5, true, false, false, "Nhà ngập 0.8m, 5 người gồm 2 trẻ em. Đang di chuyển lên tầng 2. Cần thuyền cứu hộ."),
  createSOSRequest("storm", "urgent", "acknowledged", "Hải Phòng", 0.5, 4, false, true, false, "Giông lốc tốc mái nhà, 4 người bị kẹt trong nhà hư hại. Cần hỗ trợ di tản."),
  createSOSRequest("stranded", "urgent", "resolved", "Bến Tre", 2, 3, true, false, false, "3 người bị kẹt trên ghe giữa sông do nước lũ dâng nhanh. Không thể tự bơi vào bờ."),
  createSOSRequest("flood", "urgent", "sent", "Cần Thơ", 0.7, 6, true, true, true, "Ngập nặng, 6 người trong đó có 2 trẻ em và 1 người già. Nước đang dâng. Gửi SOS qua offline."),
  createSOSRequest("landslide", "urgent", "delivered", "Đà Lạt", 1, 2, false, false, false, "Sạt lở đất nhỏ chặn đường, 2 người trên xe ô tô không thể di chuyển."),
  createSOSRequest("storm", "urgent", "queued", "Trà Vinh", 0.9, 4, true, false, true, "Mái tôn bay làm bị thương 4 người. Cần cấp cứu nhưng mất điện, không gọi được 115."),
  createSOSRequest("flood", "urgent", "dispatched", "Quảng Bình", 0.4, 7, true, true, false, "7 người bị kẹt trong trường học. Nước ngập 1m. Có trẻ em và giáo viên."),
  createSOSRequest("fire", "urgent", "acknowledged", "Đà Nẵng", 0.3, 3, false, false, false, "Cháy kho hàng gần khu dân cư. 3 hộ gia đình cần di tản. Khói độc."),
  createSOSRequest("medical", "urgent", "resolved", "Hồ Chí Minh", 1, 1, false, false, false, "Phụ nữ mang thai chuyển dạ sớm trong bão. Cần đưa đến bệnh viện."),
  createSOSRequest("stranded", "urgent", "sent", "Nha Trang", 0.6, 8, true, true, true, "8 ngư dân trên tàu cá bị hỏng máy, trôi dạt ngoài khơi. Mất liên lạc."),
  createSOSRequest("flood", "urgent", "delivered", "Huế", 0.2, 4, true, false, false, "4 người trong nhà ngập sâu. Trẻ em hoảng sợ. Cần thuyền cứu hộ."),
  createSOSRequest("trapped", "urgent", "dispatched", "Lào Cai", 0.5, 3, false, true, false, "3 người bị kẹt trong nhà do cây lớn đổ chắn đường."),

  // === NEED HELP (8) ===
  createSOSRequest("flood", "need_help", "resolved", "An Giang", 4, 3, true, false, false, "Nhà ngập nhẹ 0.3m. Cần hỗ trợ di chuyển đồ đạc lên cao. Có trẻ nhỏ."),
  createSOSRequest("storm", "need_help", "acknowledged", "Hải Phòng", 2, 2, false, false, false, "Cây đổ trước nhà, không thể ra ngoài. Cần người cắt dọn."),
  createSOSRequest("other", "need_help", "sent", "Cần Thơ", 7, 5, true, true, false, "Gia đình 5 người thiếu nước sinh hoạt 3 ngày do hạn hán. Giếng khô. Cần nước uống."),
  createSOSRequest("flood", "need_help", "delivered", "Bến Tre", 1, 4, false, true, false, "Vườn cây ăn trái ngập mặn. Cần hỗ trợ đánh giá thiệt hại."),
  createSOSRequest("storm", "need_help", "resolved", "Đà Nẵng", 3, 2, true, false, false, "Mái nhà hư hỏng nhẹ sau bão. Cần hỗ trợ sửa chữa tạm."),
  createSOSRequest("other", "need_help", "queued", "Hà Nội", 0.8, 1, false, false, true, "Mất điện 24h, thức ăn hỏng. Cần hỗ trợ thực phẩm và nước uống."),
  createSOSRequest("flood", "need_help", "sent", "Trà Vinh", 1, 6, true, true, true, "6 người cần di tản khỏi vùng ngập. Không có phương tiện."),
  createSOSRequest("landslide", "need_help", "acknowledged", "Yên Bái", 2, 3, false, false, false, "Đường sạt lở, 3 hộ gia đình bị cô lập. Cần thực phẩm và thuốc men."),
];

// ---------------------------------------------------------------------------
// MOCK EMERGENCY CONTACTS (National + 15 Provinces)
// ---------------------------------------------------------------------------

export const MOCK_NATIONAL_CONTACTS: EmergencyContact[] = [
  {
    id: generateId("EMG"),
    name: "Police",
    nameVi: "Cảnh sát - An ninh trật tự",
    number: "113",
    type: "police",
    icon: "🚔",
    color: "#3B82F6",
    available24_7: true,
    description: "Gọi khi có vấn đề về an ninh, trật tự, tai nạn giao thông",
    isNational: true,
    priority: 1,
  },
  {
    id: generateId("EMG"),
    name: "Fire Department",
    nameVi: "Cứu hỏa - Cứu nạn cứu hộ",
    number: "114",
    type: "fire",
    icon: "🚒",
    color: "#EF4444",
    available24_7: true,
    description: "Gọi khi có cháy nổ, cứu nạn cứu hộ, sự cố hóa chất",
    isNational: true,
    priority: 2,
  },
  {
    id: generateId("EMG"),
    name: "Ambulance",
    nameVi: "Cấp cứu y tế",
    number: "115",
    type: "ambulance",
    icon: "🚑",
    color: "#22C55E",
    available24_7: true,
    description: "Gọi khi cần cấp cứu y tế, tai nạn, người bị thương",
    isNational: true,
    priority: 3,
  },
  {
    id: generateId("EMG"),
    name: "Coast Guard",
    nameVi: "Biên phòng - Cứu hộ biển",
    number: "116",
    type: "coast_guard",
    icon: "⚓",
    color: "#06B6D4",
    available24_7: true,
    description: "Gọi khi cần cứu hộ trên biển, tàu thuyền gặp nạn",
    isNational: true,
    priority: 4,
  },
];

function createProvinceContacts(province: string): EmergencyContact[] {
  const base: EmergencyContact[] = [
    {
      id: generateId("EMG"),
      name: `${province} PCTT`,
      nameVi: `Ban PCTT ${province}`,
      number: `0${Math.floor(Math.random() * 900000000 + 100000000)}`,
      type: "disaster",
      icon: "🏛️",
      color: "#F59E0B",
      available24_7: true,
      description: `Ban Phòng chống thiên tai và Tìm kiếm cứu nạn tỉnh ${province}`,
      province,
      isNational: false,
      priority: 1,
    },
    {
      id: generateId("EMG"),
      name: `${province} Rescue`,
      nameVi: `Đội cứu nạn ${province}`,
      number: `0${Math.floor(Math.random() * 900000000 + 100000000)}`,
      type: "rescue",
      icon: "🚁",
      color: "#F97316",
      available24_7: true,
      description: `Đội Tìm kiếm cứu nạn chuyên nghiệp tỉnh ${province}`,
      province,
      isNational: false,
      priority: 2,
    },
    {
      id: generateId("EMG"),
      name: `${province} Red Cross`,
      nameVi: `Hội Chữ thập đỏ ${province}`,
      number: `0${Math.floor(Math.random() * 900000000 + 100000000)}`,
      type: "red_cross",
      icon: "➕",
      color: "#DC2626",
      available24_7: false,
      description: `Hội Chữ thập đỏ tỉnh ${province} - Hỗ trợ nhân đạo`,
      province,
      isNational: false,
      priority: 3,
    },
    {
      id: generateId("EMG"),
      name: `${province} Hospital`,
      nameVi: `Bệnh viện tỉnh ${province}`,
      number: `0${Math.floor(Math.random() * 900000000 + 100000000)}`,
      type: "hospital",
      icon: "🏥",
      color: "#22C55E",
      available24_7: true,
      description: `Bệnh viện đa khoa tỉnh ${province} - Cấp cứu 24/7`,
      province,
      isNational: false,
      priority: 4,
    },
  ];

  // Add coast guard for coastal provinces
  const coastalProvinces = ["Đà Nẵng", "Nha Trang", "Hải Phòng", "Bến Tre", "Trà Vinh", "Quảng Bình", "Quảng Nam"];
  if (coastalProvinces.includes(province)) {
    base.push({
      id: generateId("EMG"),
      name: `${province} Coast Guard`,
      nameVi: `Biên phòng ${province}`,
      number: `0${Math.floor(Math.random() * 900000000 + 100000000)}`,
      type: "coast_guard",
      icon: "⚓",
      color: "#06B6D4",
      available24_7: true,
      description: `Bộ đội Biên phòng tỉnh ${province} - Cứu hộ ven biển`,
      province,
      isNational: false,
      priority: 5,
    });
  }

  return base;
}

export const MOCK_PROVINCE_CONTACTS: Record<string, EmergencyContact[]> = {};
Object.keys(PROVINCE_COORDS).forEach((province) => {
  MOCK_PROVINCE_CONTACTS[province] = createProvinceContacts(province);
});

// ---------------------------------------------------------------------------
// MOCK CHECKLIST ITEMS (18 items, 6 categories)
// ---------------------------------------------------------------------------

export const MOCK_CHECKLIST_ITEMS: ChecklistItem[] = [
  // === SUPPLIES (6) ===
  {
    id: generateId("CHK"),
    category: "supplies",
    title: "Nước uống dự trữ",
    description: "Dự trữ tối thiểu 3 lít nước/người/ngày, đủ cho 3-5 ngày. Nên đóng chai PET sạch.",
    priority: "essential",
    icon: "💧",
    disasterTypes: ["flood", "storm", "drought", "earthquake", "tsunami"],
    regions: ["all"],
    season: "all",
    estimatedCost: "50,000 - 100,000 VNĐ",
    tips: "Nước đóng chai có hạn sử dụng 6 tháng. Thay thế định kỳ.",
  },
  {
    id: generateId("CHK"),
    category: "supplies",
    title: "Thực phẩm khô dự trữ",
    description: "Mì gói, bánh mì khô, lương khô, thực phẩm đóng hộp. Đủ cho 3-5 ngày.",
    priority: "essential",
    icon: "🥫",
    disasterTypes: ["flood", "storm", "drought", "earthquake"],
    regions: ["all"],
    season: "all",
    estimatedCost: "200,000 - 500,000 VNĐ",
    tips: "Chọn thực phẩm không cần nấu. Kiểm tra hạn sử dụng mỗi 3 tháng.",
  },
  {
    id: generateId("CHK"),
    category: "supplies",
    title: "Đèn pin và pin dự phòng",
    description: "Đèn pin LED công suất cao, pin dự phòng đủ dùng 3 ngày. Đèn đội đầu tiện hơn.",
    priority: "essential",
    icon: "🔦",
    disasterTypes: ["flood", "storm", "earthquake", "tsunami"],
    regions: ["all"],
    season: "all",
    estimatedCost: "100,000 - 300,000 VNĐ",
    tips: "Đèn pin đội đầu giúp rảnh tay. Pin sạc dự phòng rất hữu ích.",
  },
  {
    id: generateId("CHK"),
    category: "supplies",
    title: "Bộ sơ cứu y tế",
    description: "Băng gạc, thuốc sát trùng, thuốc giảm đau, thuốc tiêu hóa, bông y tế, kéo, găng tay.",
    priority: "essential",
    icon: "🩹",
    disasterTypes: ["flood", "storm", "landslide", "earthquake", "tsunami"],
    regions: ["all"],
    season: "all",
    estimatedCost: "150,000 - 400,000 VNĐ",
    tips: "Thêm thuốc cá nhân (tiểu đường, huyết áp...) nếu có bệnh nền.",
  },
  {
    id: generateId("CHK"),
    category: "supplies",
    title: "Áo phao / Phao cứu sinh",
    description: "Áo phao cho mỗi thành viên gia đình. Đặc biệt quan trọng cho vùng ven biển, ngập lụt.",
    priority: "essential",
    icon: "🦺",
    disasterTypes: ["flood", "tsunami"],
    regions: ["coastal", "flood_prone"],
    season: "monsoon",
    estimatedCost: "150,000 - 500,000 VNĐ",
    tips: "Áo phao phải vừa size, kiểm tra khóa kéo trước mùa mưa.",
  },
  {
    id: generateId("CHK"),
    category: "supplies",
    title: "Dây thừng cứu hộ",
    description: "Dây thừng dài 20-30m, chịu lực tốt. Hữu ích khi cần di chuyển qua vùng nước chảy.",
    priority: "recommended",
    icon: "🪢",
    disasterTypes: ["flood", "landslide"],
    regions: ["flood_prone", "mountainous"],
    season: "monsoon",
    estimatedCost: "80,000 - 200,000 VNĐ",
    tips: "Dây nylon 10mm là lựa chọn tốt. Buộc cố định trước khi bơi.",
  },

  // === DOCUMENTS (2) ===
  {
    id: generateId("CHK"),
    category: "documents",
    title: "Bản sao CCCD/Hộ khẩu",
    description: "Photocopy CCCD, hộ khẩu, giấy tờ nhà đất. Để trong túi chống nước.",
    priority: "essential",
    icon: "📄",
    disasterTypes: ["flood", "storm", "landslide", "earthquake", "tsunami", "drought"],
    regions: ["all"],
    season: "all",
    tips: "Chụp ảnh lưu trên điện thoại làm backup. Để túi chống nước riêng.",
  },
  {
    id: generateId("CHK"),
    category: "documents",
    title: "Tiền mặt dự phòng",
    description: "Dự trữ 1-2 triệu tiền mặt. ATM có thể không hoạt động khi mất điện.",
    priority: "recommended",
    icon: "💰",
    disasterTypes: ["flood", "storm", "earthquake", "tsunami"],
    regions: ["all"],
    season: "all",
    estimatedCost: "1,000,000 - 2,000,000 VNĐ",
    tips: "Tiền mệnh giá nhỏ (10k, 20k, 50k) tiện hơn khi mua nhu yếu phẩm.",
  },

  // === HOME (3) ===
  {
    id: generateId("CHK"),
    category: "home",
    title: "Gia cố nhà cửa",
    description: "Kiểm tra mái nhà, cửa sổ, cửa chính. Gia cố bằng dây neo, đinh vít. Cắt bỏ cành cây gần nhà.",
    priority: "essential",
    icon: "🏠",
    disasterTypes: ["storm", "flood"],
    regions: ["all"],
    season: "typhoon",
    tips: "Kiểm tra mỗi đầu mùa bão. Gia cố mái bằng dây thép neo vào tường.",
  },
  {
    id: generateId("CHK"),
    category: "home",
    title: "Nâng đồ lên cao",
    description: "Di chuyển đồ điện tử, giấy tờ, quần áo lên tầng cao hoặc kệ cao trên 1m.",
    priority: "recommended",
    icon: "📦",
    disasterTypes: ["flood"],
    regions: ["flood_prone", "delta"],
    season: "monsoon",
    tips: "Ưu tiên: giấy tờ > điện tử > quần áo > thực phẩm.",
  },
  {
    id: generateId("CHK"),
    category: "home",
    title: "Chuẩn bị bao cát",
    description: "Dự trữ 10-20 bao cát để chắn nước tràn vào nhà. Có thể mua sẵn hoặc tự đóng.",
    priority: "recommended",
    icon: "🏗️",
    disasterTypes: ["flood"],
    regions: ["flood_prone", "delta", "coastal"],
    season: "monsoon",
    estimatedCost: "100,000 - 300,000 VNĐ",
    tips: "Đặt bao cát trước cửa ra vào, cửa sổ hướng nước chảy.",
  },

  // === COMMUNICATION (3) ===
  {
    id: generateId("CHK"),
    category: "communication",
    title: "Sạc đầy pin điện thoại",
    description: "Sạc đầy pin điện thoại + sạc dự phòng. Tải app CuuNet và app cảnh báo thiên tai.",
    priority: "essential",
    icon: "📱",
    disasterTypes: ["flood", "storm", "landslide", "earthquake", "tsunami", "drought"],
    regions: ["all"],
    season: "all",
    tips: "Sạc dự phòng 20,000mAh sạc được 4-5 lần điện thoại.",
  },
  {
    id: generateId("CHK"),
    category: "communication",
    title: "Radio cầm tay",
    description: "Radio FM/AM cầm tay để nghe bản tin khi mất điện, mất sóng điện thoại.",
    priority: "recommended",
    icon: "📻",
    disasterTypes: ["flood", "storm", "earthquake", "tsunami"],
    regions: ["mountainous"],
    season: "all",
    estimatedCost: "100,000 - 300,000 VNĐ",
    tips: "Pin AA dễ tìm hơn pin sạc. Tần số Đài Tiếng nói VN: FM 99.5MHz.",
  },
  {
    id: generateId("CHK"),
    category: "communication",
    title: "Danh bạ khẩn cấp",
    description: "Ghi lại số điện thoại khẩn cấp: 113, 114, 115, 116. Số người thân, hàng xóm.",
    priority: "essential",
    icon: "📞",
    disasterTypes: ["flood", "storm", "landslide", "earthquake", "tsunami", "drought"],
    regions: ["all"],
    season: "all",
    tips: "In ra giấy, dán ở nơi dễ thấy. Lưu trong điện thoại mục 'ICE' (In Case of Emergency).",
  },

  // === EVACUATION (2) ===
  {
    id: generateId("CHK"),
    category: "evacuation",
    title: "Xác định đường sơ tán",
    description: "Biết đường sơ tán gần nhất đến nơi cao ráo, an toàn. Tập đi thử 1 lần.",
    priority: "essential",
    icon: "🏃",
    disasterTypes: ["flood", "storm", "landslide", "tsunami"],
    regions: ["all"],
    season: "all",
    tips: "Đường sơ tán phải tránh sông, suối, taluy. Nơi tập trung thường là trường học, UBND xã.",
  },
  {
    id: generateId("CHK"),
    category: "evacuation",
    title: "Túi đồ sơ tán (Go-Bag)",
    description: "Túi balo sẵn sàng mang đi: nước, thực phẩm, đèn pin, radio, giấy tờ, thuốc, tiền mặt, áo mưa.",
    priority: "essential",
    icon: "🎒",
    disasterTypes: ["flood", "storm", "landslide", "earthquake", "tsunami"],
    regions: ["all"],
    season: "all",
    estimatedCost: "500,000 - 1,000,000 VNĐ",
    tips: "Cập nhật mỗi 3 tháng. Thay nước và thực phẩm hết hạn. Để gần cửa ra.",
  },

  // === HEALTH (2) ===
  {
    id: generateId("CHK"),
    category: "health",
    title: "Thuốc cá nhân",
    description: "Dự trữ thuốc bệnh nền (tiểu đường, huyết áp, tim mạch...) đủ 7-14 ngày. Kê đơn sẵn.",
    priority: "essential",
    icon: "💊",
    disasterTypes: ["flood", "storm", "landslide", "earthquake", "tsunami", "drought"],
    regions: ["all"],
    season: "all",
    tips: "Mang theo đơn thuốc. Thông báo tình trạng bệnh cho đội cứu hộ khi SOS.",
  },
  {
    id: generateId("CHK"),
    category: "health",
    title: "Xử lý nước sạch",
    description: "Viên lọc nước hoặc máy lọc nước mini. Nước lũ bị ô nhiễm nặng, không thể uống trực tiếp.",
    priority: "recommended",
    icon: "🧪",
    disasterTypes: ["flood", "drought"],
    regions: ["flood_prone", "delta"],
    season: "monsoon",
    estimatedCost: "50,000 - 200,000 VNĐ",
    tips: "Viên Aquatabs diệt 99.9% vi khuẩn. 1 viên/1 lít nước, chờ 30 phút.",
  },
];

// ---------------------------------------------------------------------------
// MOCK STATS (pre-calculated for dashboard)
// ---------------------------------------------------------------------------

export const MOCK_ALERT_STATS = {
  totalActive: MOCK_ALERTS.filter((a) => a.status === "actual").length,
  extremeCount: MOCK_ALERTS.filter((a) => a.info.severity === "extreme").length,
  severeCount: MOCK_ALERTS.filter((a) => a.info.severity === "severe").length,
  moderateCount: MOCK_ALERTS.filter((a) => a.info.severity === "moderate").length,
  minorCount: MOCK_ALERTS.filter((a) => a.info.severity === "minor").length,
  pendingSOS: MOCK_SOS_REQUESTS.filter((s) => ["queued", "sent", "delivered"].includes(s.status)).length,
  resolvedTodaySOS: MOCK_SOS_REQUESTS.filter((s) => s.status === "resolved" && s.resolvedAt && new Date(s.resolvedAt).toDateString() === new Date().toDateString()).length,
  totalAlertsThisWeek: 12,
  checklistCompletionAvg: 45,
  topDisasterType: "flood" as DisasterType,
  topProvince: "Quảng Bình",
  alertsByType: {
    flood: 8,
    storm: 5,
    landslide: 3,
    drought: 2,
    earthquake: 1,
    tsunami: 1,
  } as Record<DisasterType, number>,
  alertsBySeverity: {
    extreme: 4,
    severe: 6,
    moderate: 6,
    minor: 4,
  } as Record<AlertSeverity, number>,
  alertsByProvince: {
    "Quảng Bình": 3,
    "Đà Nẵng": 3,
    "Huế": 3,
    "Hồ Chí Minh": 3,
    "Hà Nội": 3,
    "Lào Cai": 2,
    "Yên Bái": 2,
    "Nha Trang": 2,
    "Hải Phòng": 2,
    "Cần Thơ": 2,
    "An Giang": 2,
    "Bến Tre": 2,
    "Trà Vinh": 2,
    "Đà Lạt": 2,
    "Quảng Nam": 2,
  } as Record<string, number>,
  sosByStatus: {
    queued: MOCK_SOS_REQUESTS.filter((s) => s.status === "queued").length,
    sent: MOCK_SOS_REQUESTS.filter((s) => s.status === "sent").length,
    delivered: MOCK_SOS_REQUESTS.filter((s) => s.status === "delivered").length,
    acknowledged: MOCK_SOS_REQUESTS.filter((s) => s.status === "acknowledged").length,
    dispatched: MOCK_SOS_REQUESTS.filter((s) => s.status === "dispatched").length,
    resolved: MOCK_SOS_REQUESTS.filter((s) => s.status === "resolved").length,
    failed: MOCK_SOS_REQUESTS.filter((s) => s.status === "failed").length,
  } as Record<SOSStatus, number>,
  sosByType: {
    flood: MOCK_SOS_REQUESTS.filter((s) => s.situation.type === "flood").length,
    storm: MOCK_SOS_REQUESTS.filter((s) => s.situation.type === "storm").length,
    landslide: MOCK_SOS_REQUESTS.filter((s) => s.situation.type === "landslide").length,
    fire: MOCK_SOS_REQUESTS.filter((s) => s.situation.type === "fire").length,
    medical: MOCK_SOS_REQUESTS.filter((s) => s.situation.type === "medical").length,
    trapped: MOCK_SOS_REQUESTS.filter((s) => s.situation.type === "trapped").length,
    stranded: MOCK_SOS_REQUESTS.filter((s) => s.situation.type === "stranded").length,
    earthquake: MOCK_SOS_REQUESTS.filter((s) => s.situation.type === "earthquake").length,
    tsunami: MOCK_SOS_REQUESTS.filter((s) => s.situation.type === "tsunami").length,
    other: MOCK_SOS_REQUESTS.filter((s) => s.situation.type === "other").length,
  } as Record<SOSType, number>,
  recentTrend: "increasing" as const,
  averageResponseTime: 18,
  onlineUserCount: 12450,
};
